server:
  port: 8181
  address: 0.0.0.0  # Thêm dòng này để ứng dụng có thể nhận request từ bên ngoài

spring:
  config:
    activate:
      on-profile: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/PBL6
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:/db/migration
    baseline-on-migrate: true
    baseline-version: 0
  jackson:
    date-format: yyyy-MM-dd
    time-zone: UTC
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

#payment:
#  vnPay:
#    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
#    tmnCode: Y7AUI2TQ
#    secretKey: 5GJ91M1F4B7SL17JOWRYUATA7RL47U1N
#    returnUrl: http://localhost:8181/api/payment/vn-pay-callback
#    version: 2.1.0
#    command: pay
#    orderType: other


